MvcProject/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class AboutUsController : Controller
    {
        //
        // GET: /AboutUs/

        public ActionResult ContactUs()
        {
            return View();
        }

    }
}

MvcProject/Controllers/AdminController.cs
using MvcProject.Business;
using MvcProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        private IBusinessCar iBusiness = null;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            iBusiness = new BusinessCar();

            base.Initialize(requestContext);
        }
        public ActionResult AdminView()
        {
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            AdminModel model = new AdminModel();
           // CarResultsModel model = new CarResultsModel();
            model.maketypes = carM;
                   
            List<CarCategory> Cat = iBusiness.CarCat();
            model.carCat = Cat;
            return View(model);
        }

        public ActionResult UpdateCar()
        {
            
            return View();
        }

        public ActionResult DeleteCar()
        {
            AdminModel model = new AdminModel();
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            model.maketypes = carM;

            List<CarCategory> Cat = iBusiness.CarCat();
            model.carCat = Cat;
            return View(model);
        }
        [HttpPost]
        public ActionResult DeleteCar(AdminModel model)
        {
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            model.maketypes = carM;

            List<CarCategory> Cat = iBusiness.CarCat();
            model.carCat = Cat;

            string make = Request.Form["maketypes"].ToString();
            model.maketypes1 = new CarMakeModel();
            model.carDetails1 = new CarFullInfoModel();
            model.maketypes1.Make = make;
            string cModel = Request.Form["ddlModel"].ToString();
            model.carDetails1.Model = cModel;

            if(iBusiness.DeleteCar(model))
            {
                model.Status = "Delete Successful";
            }

            else
            {
                model.Status = "Failed to delete";
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AdminView(AdminModel model)
        {
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            //AdminModel model = new AdminModel();
            // CarResultsModel model = new CarResultsModel();
            model.maketypes = carM;

            List<CarCategory> Cat = iBusiness.CarCat();
            model.carCat = Cat;
            
            // when you fetch carCat
            int catID = Convert.ToInt32(Request.Form["carCat"]);
            model.carCat1 = new CarCategory();
            model.carCat1.catId = catID;
            //if (ModelState.IsValid)
            if (model.maketypes1.Make == null && model.carDetails1.Model == null && model.carDetails1.Year == 0 && model.carDetails1.Price == 0.0 && model.carDetails1.Mileage == null)
            {
                model.Status = "Fill all of the Fields above in the form";
            }
            else
            {
                
                {
                    if (iBusiness.AddNewCar(model))
                    {
                        ModelState.Clear();
                        model.Status = "Car information has been added successfully.";

                    }
                    else
                        model.Status = "Car could not be added.";
                }
                
            }
            return View(model);
        }
        public ActionResult CarModel(string value)
        {


            List<SearchCar> carsList = null;
            //value = Request.Form["ddlMake"].ToString();

            carsList = iBusiness.Cars(value);
            // CarResultsModel model = new CarResultsModel();
            //carModel.sCar = carsList;
            SelectList objList = new SelectList(carsList, "Id", "Model", 0);

            return Json(objList);
        }

        //public ActionResult CarDetails()
        //{
        //    //List<CarMakeModel> carM = null;
        //    //carM = iBusiness.CarMake();
        //    //AdminModel model = new AdminModel();
        //    //model.maketypes=carM;
            
        //    //return PartialView(model);
        //}

    }
}

MvcProject/Controllers/CarsController.cs
using MvcProject.Business;
using MvcProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class CarsController : Controller
    {
        //
        // GET: /Cars/
        private IBusinessCar iBusiness = null;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            iBusiness = new BusinessCar();
             
            base.Initialize(requestContext);
        }

        //public ActionResult SearchCar()
        //{
        //    SearchCar model = new SearchCar();
        //    return View(model);
        //}
        //public ActionResult SearchCar()
        //{
            
        //    //SearchCar model = new SearchCar();
        //    //return View("SearchCar");
        //}

        public ActionResult SearchForCar()
        {
            //List<SearchCar> carsList = null;
           
            //carsList = iBusiness.Cars();
            //CarResultsModel model = new CarResultsModel();
            //model.sCar = carsList;
            //return View(model);
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            CarResultsModel model = new CarResultsModel();
            model.carMake = carM;
            return View(model);
        }

        public ActionResult CarModelInfo(string value)
        {


            List<SearchCar> carsList = null;
           //value = Request.Form["ddlMake"].ToString();
            
            carsList = iBusiness.Cars(value);
            // CarResultsModel model = new CarResultsModel();
            //carModel.sCar = carsList;
            SelectList objList = new SelectList(carsList, "Id", "Model", 0);

            return Json(objList);
        }

        public ActionResult CarYearInfo(string value)
        {


            List<SearchCar> carsList = null;
            //value = Request.Form["ddlMake"].ToString();

            carsList = iBusiness.Cars(value);
            // CarResultsModel model = new CarResultsModel();
            //carModel.sCar = carsList;
            SelectList objList = new SelectList(carsList, "Id", "Year", 0);

            return Json(objList);
        }

        public ActionResult CarPriceInfo(string value)
        {


            List<SearchCar> carsList = null;
            //value = Request.Form["ddlMake"].ToString();

            carsList = iBusiness.Cars(value);
            // CarResultsModel model = new CarResultsModel();
            //carModel.sCar = carsList;
            SelectList objList = new SelectList(carsList, "Id", "Price", 0);

            return Json(objList);
        }

        [HttpPost]
        public ActionResult SearchForCar(CarResultsModel CarResModel)
        {
            List<CarMakeModel> carM = null;
            carM = iBusiness.CarMake();
            CarResModel.carMake = carM;

            //List<SearchCar> carsList = null;
            //int i = 1;
            //carsList = iBusiness.Cars();
            //CarResultsModel cmodel = new CarResultsModel();
           // CarResModel.sCar = carsList;

            //List<SearchCar> carsList = null;
            //string make = Request.Form["makeListbox"].ToString();
            //carsList = iBusiness.Cars(make);
            // CarResultsModel model = new CarResultsModel();
            //CarResModel.sCar = carsList;

            List<CarFullInfoModel> CList = null;
            //int make = Convert.ToInt32(Request.Form["makeListbox"].ToString());
            string make = Request.Form["carMake"].ToString();
            string model = Request.Form["ddlModel"].ToString();
            int year = Convert.ToInt32(Request.Form["ddlYear"]);
            double price = Convert.ToDouble(Request.Form["ddlPrice"]);
            CList = iBusiness.quickSearchResults(make, model, year, price);
            CarResModel.carInfo = CList;
            return View(CarResModel);
        }

        //[HttpPost]
        //public ActionResult SearchCar(SearchCar scar)
        //{
        //    List<SearchCar> CList = null;
        //    string make = Request.Form["makeListbox"].ToString();
        //    string model = Request.Form["modelListbox"].ToString();
        //    int year = Convert.ToInt32(Request.Form["yearListbox"]);
        //    double price = Convert.ToDouble(Request.Form["priceListbox"]);
        //    CList = iBusiness.quickSearchResults(make, model, year, price);
        //    return View(CList);
        //}
        //public ActionResult CarInfo()
        //{
            
        //    List<SearchCar> carsList = null;
        //    //int i = 1;
        //    carsList = iBusiness.Cars();
        //    return View(carsList);
        //}

        public ActionResult ViewUsedCars(CarResultsModel CarResModel)
        {
            List<CarFullInfoModel> UsedCars = null;
            UsedCars=iBusiness.ViewUsedCars();
           // CarFullInfoModel model = new CarFullInfoModel();
           // model = UsedCars;
            CarResModel.carInfo = UsedCars;
            return View(CarResModel);
        }

        public ActionResult ViewNewCars(CarResultsModel CarResModel)
        {
            List<CarFullInfoModel> NewCars = null;
            NewCars = iBusiness.ViewNewCars();
            // CarFullInfoModel model = new CarFullInfoModel();
            // model = UsedCars;
            CarResModel.carInfo = NewCars;
            return View(CarResModel);
        }

        public ActionResult ViewUsedCarsUnder(CarResultsModel CarResModel)
        {
            List<CarFullInfoModel> UsedCarsUnder = null;
            UsedCarsUnder = iBusiness.ViewUsedCarsUnder();
            // CarFullInfoModel model = new CarFullInfoModel();
            // model = UsedCars;
            CarResModel.carInfo = UsedCarsUnder;
            return View(CarResModel);
        }



    }
}

MvcProject/Views/Shared/AdminView.cshtml
@model MvcProject.Models.AdminModel

@{
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

@section TitleContent{
    MyView
}


@section ContentBody{
    @using (Html.BeginForm("AdminView", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
<html>
<head>
    <title></title>
    <style>
        #adminBody{
            height:700px;
            width:1000px;
            margin:auto;
            background-color:#87CEEB;
        }
        #adminMenu{
            height:45px;
            width:1000px;
            background-color:#6A5ACD;
        }

        #adminPanel{
            height:auto;
            width:980px;
        
        }
          
         ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 26px;
    text-decoration: none;
}

li a:hover {
    background-color: #440044;
    color:white;
}
    </style>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    </head>
        <body>
            <div id="adminBody">
                <div id="adminMenu">
                   <ul>
                    
                    <li>
                    <li><a href="@Url.Action("AdminView", "Admin")">ADD NEW CAR</a></li>
                    <li><a href="@Url.Action("UpdateCar", "Admin")">UPDATE CAR INFO</a></li>
                    <li><a href="@Url.Action("DeleteCar", "Admin")">DELETE CAR INFO</a></li>
                   </ul>
               </div>
                <div id="adminPanel">

                    <h3 style="text-align:right;">Welcome @Session["loggedIn"]</h3>
                    <br />
                    
                    <div id="AdminMainView">

                        <center>
                            <h4>ADD NEW CAR</h4>
                            <h3> @Html.ValueFor(model => model.Status) </h3>
                            <table>
                                @*<tr>
                                    <td style ="width:60px; height:50px;">Make</td>
                                   <td>@Html.DropDownListFor(model => model.maketypes, new SelectList(Model.maketypes, "MakeId", "Make"), new
                            {
                                @class = "form-control",
                                @id = "ddlCarMake",
                                @style = "width:200px;",
                                @onchange = "javascript:GetCarInfo(this.value);"
                            })</td>
                                    <td></td>
                                </tr>*@
                                <tr>
                                    <td align="right" style="width:60px; height:50px;">
                                        Make
                                        @*@Html.DisplayNameFor(model => model.maketypes)*@
                                    </td>
                                    <td style="width:60px; height:50px;">
                                        @Html.EditorFor(model => model.maketypes1.Make, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>
                                    <td>
                                        @Html.ValidationMessageFor(model => model.maketypes1.Make)
                                    </td>
                                </tr>

                                <tr>
                                    <td align="right" style="width:60px; height:50px;">
                                        Model
                                        @*@Html.DisplayNameFor(model => model.maketypes)*@
                                    </td>
                                    <td style="width:60px; height:50px;">
                                        @Html.EditorFor(model => model.carDetails1.Model, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>
                                    <td>
                                        @Html.ValidationMessageFor(model => model.carDetails1.Model)
                                    </td>
                                </tr>
                                @*<tr>
                                <td style="width:60px; height:50px;">
                                    Model
                                </td>
                                <td style="width:60px;">
                                    <select class="form-control" id="ddlModel2" name="ddlModel2" style="width: 200px"></select>
                                    </td>
                                    <td></td>
                                    </tr>*@
                                <tr>
                                    <td align="right" style="width:60px; height:50px;">
                                        Year
                                        @*@Html.DisplayNameFor(model => model.maketypes)*@
                                    </td>
                                    <td style="width:60px; height:50px;">
                                        @Html.EditorFor(model => model.carDetails1.Year, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>
                                    <td>
                                        @Html.ValidationMessageFor(model => model.carDetails1.Year)
                                    </td>
                                </tr>

                                <tr>
                                    <td align="right" style="width:60px; height:50px;">
                                        Price
                                        @*@Html.DisplayNameFor(model => model.maketypes)*@
                                    </td>
                                    <td style="width:60px; height:50px;">
                                        @Html.EditorFor(model => model.carDetails1.Price, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>
                                    <td>
                                        @Html.ValidationMessageFor(model => model.carDetails1.Price)
                                    </td>
                                </tr>

                                <tr>
                                    <td style="width:60px; height:50px;">Mileage</td>
                                    <td style="width:60px; height:50px;">
                                        @Html.EditorFor(model => model.carDetails1.Mileage, new { htmlAttributes = new { @class = "form-control" } })
                                    </td>
                                    <td>
                                        @Html.ValidationMessageFor(model => model.carDetails1.Mileage)
                                    </td>
                                </tr>

                                <tr>
                                    <td style="width:60px; height:50px;">Category</td>
                                    <td style="width:60px; height:50px;">

                                        
                                        @Html.DropDownListFor(model => model.carCat, new SelectList(Model.carCat, "catId", "catName"), new
                                        {
                                            @class = "form-control",
                                            @id = "ddlCat2"
                                        })
                                    </td>
                                    <td></td>
                                    </tr>

                                <tr>
                                    <td style="width:60px; height:50px;">Body Type</td>
                                    <td>
                                        @{
                                        List<SelectListItem> listItems = new List<SelectListItem>();
                                        listItems.Add(new SelectListItem
                                            {
                                                Text = "--Select--",
                                                Value = "0",
                                                Selected = true
                                            });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Sedan",
                                            Value = "Sedan",
                                           
                                        });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Convertible",
                                            Value = "Convertible",
                                           
                                        });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "PickUpTruck",
                                            Value = "PickUpTruck",
                                           
                                        });
                                @Html.DropDownListFor(model => model.carDetails1.BodyStyle, listItems, new { @class = "form-control" })


                                        }
                                    </td>
                                    
                                    @*<td style="width:60px; height:50px;">
                                        <select class="form-control" id="carType">
                                            <option value="Sedan">Sedan</option>
                                            <option value="Convertible">Convertible</option>
                                            <option value="PickUpTruck">Pick Up Truck</option>
                                        </select>
                                    </td>*@

                             </tr>
                                <tr>
                                    <td>
                                <tr>
                                    <td align="right" style="width:60px; height:50px;">
                                        @Html.DisplayNameFor(model => model.imgModel1.ImageFile)
                                    </td>
                                    <td style="width:60px; height:50px;">

                                        @Html.TextBoxFor(model => model.imgModel1.ImageFile, new { type = "file" })
                                    </td>
                                    <td>
                                        @*@Html.ValidationMessageFor(m => m.Image)*@
                                    </td>
                                </tr>
                                <tr>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td><input type="submit" value="Insert" id="btnInsertCar" /></td>
                                </tr>
                               
                                  

                          </table>
                            
                        </center>
                        
                    </div>
                   
                </div>
                
                
                 
            </div>
        </body>
        
</html>
        
    }
    }

MvcProject/Views/Shared/Footer.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Stylesheet/footerStyles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    
    <div id="foot" style="background-color:#E6E6FA; height:50px; width:1000px; margin:auto;">

    </div>

</body>
</html> 

MvcProject/Views/Shared/Header.cshtml
<html>
 <head>
     <title></title>
     <style>

         ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 26px;
    text-decoration: none;
}

li a:hover {
    background-color: #440044;
    color:white;
}
.nav li ul {
    position:absolute;
    display:none;
    width:inherit;
	text-align:left;
}
.nav li:hover ul {
    display:block;
}

.nav ul li ul li {
  display: block;
  float:none !important; /* newly added */
  height:auto; /* newly added */
  line-height:24px; /* newly added */
  background-color:pink;
}
  
        </style>
 </head>
<body>
    <div id="topHeader" style="background-color:#E6E6FA; height:70px; width:1000px; margin:auto;">
        <p style="text-align:right;">@Session["loggedIn"]</p>
    </div>
    
    <div class="nav" style="background-color:rebeccapurple;  height:45px; width:1000px; margin:auto;">
        <ul >
            <li style="color:white;"><a href="@Url.Action("HomePage", "Home")">HOME</a></li>
            <li><a href="#news">INVENTORY</a>
                 <ul><li><a href="@Url.Action("ViewUsedCars", "Cars")">VIEW USED CARS</a></li>
                     <li><a href="@Url.Action("ViewNewCars", "Cars")">VIEW NEW CARS</a></li>
                     <li><a href="@Url.Action("ViewUsedCarsUnder", "Cars")">USED CARS UNDER $10000</a></li></ul></li>
            <li><a href="#contact">FINANCE</a>
                <ul>
                    <li><a href="@Url.Action("", "")">FINANCE WARRANTIES</a></li>
                    <li><a href="@Url.Action("Finance", "Finance")">APPLY ONLINE</a></li>
                    <li><a href="@Url.Action("ViewUsedCarsUnder", "Cars")">LOAN CALCULATOR</a></li>
                </ul></li>
            <li><a href="#about">ABOUT US</a>
                <ul>
                    <li><a href="#">OUR STAFF</a></li>
                    <li><a href="@Url.Action("ContactUs", "AboutUs")">CONTACT US</a></li>
                    
                </ul></li>
            <li><a href="#about">REVIEWS</a></li>
            <li><a href="#about">SERVICE DEPARTMENT</a>
                <ul>
                    <li><a href="@Url.Action("ServiceEstimate", "CarService")">GET SERVICE ESTIMATE</a></li>
                    <li><a href="#">FIND A SERVICE CENTER</a></li>
                    <li><a href="@Url.Action("Appointment", "ScheduleAppointment")">SCHEDULE AN APPOINTMENT</a></li>
                </ul></li>
            <li><a href="@Url.Action("Gallery", "Home")">GALLERY</a></li>
        </ul>

    </div>
</body>
</html>

MvcProject/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@RenderSection("TitleContent", false)</title>
    
    @RenderSection("HeaderSection", false)
    <link href="~/Stylesheet/MyLayout.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
    $(document).ready(function () {
        $(".login").click(function () {
            $("#SignUp").hide();
            $("#Login").show();
        });
        $(".signUp").click(function () {
            $("#Login").hide();
            $("#SignUp").show();
        });
        
        //$("#btnCarSearch").click(function () {
        //    $("#CarSearch").hide();
        //    $("#SearchResults").show();
        //});
       
    });
    function GetOtherCarInfo(_make) {
        //var promessage ="<option value ='0'>Please wait...</option>";
        // $("#").html(promessage).show();
        var url = "http://localhost:50664/Cars/CarModelInfo";
        $.ajax({
            url: url,
            data: { value: _make },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Model</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Text + ">" + data[x].Text + "</option>";
                }
                $("#ddlModel").html(markup).show();
            },
            error: function (response) {
                alert("error : " + response);
            }
        });
    }

    function GetCarInfo(_make) {
        alert("fbxcvhdhf");
        //var promessage ="<option value ='0'>Please wait...</option>";
        // $("#").html(promessage).show();
        var url = "http://localhost:50664/Admin/CarModel";
        $.ajax({
            url: url,
            data: { value: _make },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Model</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Text + ">" + data[x].Text + "</option>";
                }
                $("#ddlModel2").html(markup).show();
            },
            error: function (response) {
                alert("error : " + response);
            }
        });
    }
    function GetOtherCarInfo1(_make) {
        //var promessage ="<option value ='0'>Please wait...</option>";
        // $("#").html(promessage).show();
        var url = "http://localhost:50664/Cars/CarYearInfo";
        $.ajax({
            url: url,
            data: { value: _make },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Year</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Text + ">" + data[x].Text + "</option>";
                }
                $("#ddlYear").html(markup).show();
            },
            error: function (response) {
                alert("error : " + response);
            }
        });
    }
    function GetOtherCarInfo2(_make) {
        //var promessage ="<option value ='0'>Please wait...</option>";
        // $("#").html(promessage).show();
        var url = "http://localhost:50664/Cars/CarPriceInfo";
        $.ajax({
            url: url,
            data: { value: _make },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Price</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Text + ">" + data[x].Text + "</option>";
                }
                $("#ddlPrice").html(markup).show();
            },
            error: function (response) {
                alert("error : " + response);
            }
        });
    }

    function GetServiceCat(_cat) {
        //var promessage ="<option value ='0'>Please wait...</option>";
        // $("#").html(promessage).show();
        var url = "http://localhost:50664/CarService/ServiceCat";
        $.ajax({
            url: url,
            data: {value:_cat },
            cache: false,
            type: "POST",
            success: function (data) {
                var markup = "<option value='0'>Select Service</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Text + ">\"" + data[x].Text + "\"</option>";
                }
                $("#ddlService").html(markup).show();
            },
            error: function (response) {
                alert(_cat);
                alert("error : " + response);
            }
        });
    }
    </script>
    <script>
    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
        showDivs(slideIndex += n);
    }

    function currentDiv(n) {
        showDivs(slideIndex = n);
    }

    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("demo");
        if (n > x.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = x.length }
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
        }
        x[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " w3-opacity-off";
    }
    </script>

    </head>
    <body>

        @Html.Partial("Header")
        <div>
            @RenderSection("ContentBody", false)

        </div>
        @Html.Partial("Footer")
    </body>
    </html>